twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images': images
        '%kernel.project_dir%/public/css': styles

when@test:
    twig:
        strict_variables: true
